// assets/svelte/BlogPostCard.svelte
<div class="flex flex-col relative w-72 my-5 bg-surface-800 blog-post">
  <a target="_blank" rel="noreferrer" underline="none" href="#df">
    <div class="background-box bg-surface-700/70 bg-cover bg-center" />
    <div class="flex flex-col justify-between flex-1 p-5">
      <h2 class="text-xl">title</h2>
      <p class="mt-8 text-primary-600">creator</p>
    </div>
  </a>
</div>

<style>
  p {
    font-weight: bold;
    text-transform: uppercase;
    font-size: 0.75rem;
    letter-spacing: 0.05em;
  }

  .blog-post {
    @media screen and (max-width: 37.5rem) {
      width: 90vw;
    }
  }

  .background-box {
    padding-bottom: 60%;
  }
</style>

// src/components/blocks/BlogPostCard.tsx
import { Box, Link, Typography, useTheme } from "@mui/material";

const BlogPostCard = ({ blog }) => {
  const theme = useTheme();

  return (
    <Box
      sx={{
        alignSelf: "flex-start",
        position: "relative",
        width: "20rem",
        minWidth: "17.18rem",
        margin: "1.25rem 0.75rem",
        // background: theme.palette.background.default,
        boxShadow: `0.2rem 0.2rem 10rem ${theme.palette.secondary.main}`,
      }}
    >
      <Box>
        <Link
          target="_blank"
          rel="noreferrer"
          underline="none"
          href={blog.link}
        >
          <Box
            sx={{
              paddingBottom: "60%",
              backgroundSize: "cover",
              backgroundPosition: "center center",
              background: theme.palette.secondary.light,
            }}
          ></Box>
          <Box
            sx={{
              padding: "1.25rem",
              flex: "1",
              display: "flex",
              flexDirection: "column",
              justifyContent: "space-between",
            }}
          >
            <Typography
              sx={{
                fontSize: "1.25rem",
                color: theme.palette.primary.dark,
              }}
            >
              {blog.title}
            </Typography>
            <Typography
              sx={{
                fontWeight: "bold",
                textTransform: "uppercase",
                fontSize: "0.75rem",
                letterSpacing: "0.05em",
                marginTop: "2rem",
                color: theme.palette.secondary.dark,
              }}
            >
              {blog.creator}
            </Typography>
          </Box>
        </Link>
      </Box>
    </Box>
  );
};

export default BlogPostCard;
